### ISSUE TITLE
internal error 131

### ISSUE THREAD

**Issue by zer0fl0w** [j-fbriere/squawker#101]
![Screenshot_20231031-101355_1](https://github.com/j-fbriere/squawker/assets/36411173/59d24c43-1baf-4733-bc50-3dca2a585c53)

i get this error since today everytime refreshing feed. feed still loads new tweets. so i do not really know what it means. just wanted to mention it.

**Comment by j-fbriere** [comment]
I got the same error last week.
It went off and on for a day.
Then it disappeared t never come back.
It is an internal error that comes from from Twitter/X.
I did some research but there is very little info about this error.

**Comment by zer0fl0w** [comment]
thx for letting me know.
