### ISSUE TITLE
Add an option to replace the domain when copying tweet links

### ISSUE THREAD

**Issue by sudoshindo** [j-fbriere/squawker#103]
### Describe the problem

Twitter embeds often fail to show up when posted in various places (e.g. Discord).

The common solution me and the people I talk to resort to is using domains like vxtwitter or fixvx.

### Describe the solution

I want to request a setting for the app.

I would call it something like *Custom domain when sharing*.

It would be a text box where you can write the domain you want to use (e.g. vxtwitter.com)

When configured, pressing *Share tweet link* will now replace twitter.com with whatever the user specified.

**ALTERNATIVE**

Make the option an on/off switch instead, and it will always use vxtwitter.com if turned on.

Pro: Much simpler.

Con: If vxtwitter ever breaks the user can't easily switch domains. It needs to be changed on the developer side.

**Comment by matterharz** [comment]
![image1](https://github.com/j-fbriere/squawker/assets/76849821/ff81bf9c-1c45-4b62-a735-508bfea9b0d6)

**Comment by sudoshindo** [comment]
Damn it, I'm blind. Sorry.
