### ISSUE TITLE
Add a subscribe to all button 

### ISSUE THREAD

**Issue by williamdes** [j-fbriere/squawker#107]
### Describe the problem

This app is awesome!
I found it on F-Droid today.
Could you add a button so can in one click subscribe to all the accounts one twitter account is subscribed to?

This is for me to not have to click hundreds or hundreds of times on subscribe using my Twitter account as a list of accounts to follow 

### Describe the solution

Add a button or feature to subscribe to all subscriptions of an account

**Comment by j-fbriere** [comment]
There is already the _Import from Twitter/X_ link when the subscription list is empty.
Do you mean a use case when there is already some existing subscriptions and then you want to add all subscriptions from a Twitter/X account?

**Comment by williamdes** [comment]
> There is already the _Import from Twitter/X_ link when the subscription list is empty. Do you mean a use case when there is already some existing subscriptions and then you want to add all subscriptions from a Twitter/X account?

Where is it?
Maybe it should always be available

One scenario is you want to import a friend's twitter account subscriptions or if you have multiple accounts you will want to subscribe to all the stuff from all accounts

**Comment by j-fbriere** [comment]
> Where is it?
In the subscription list screen (second screen after the Feed screen), only when there are no subscription.

> Maybe it should always be available
So I understand this is the feature requested: That the functionality to import from Twitter/X account always be available, not only when there are no subscription.

**Comment by williamdes** [comment]
> So I understand this is the feature requested: That the functionality to import from Twitter/X account always be available, not only when there are no subscription.

yes

**Comment by j-fbriere** [comment]
It's kinda embarrassing for me to admit, but after some analysis to add a button for this functionality, I discovered that there is already one.
You see, I never use this functionality.
Here it is in the Subscriptions screen, the first icon with arrows:
![Screenshot_20231116-133948_Squawker_small](https://github.com/j-fbriere/squawker/assets/49044668/c9d67d71-16bc-450c-83c1-0d640292be59)

**Comment by williamdes** [comment]
Wow..
this icon (https://api.flutter.dev/flutter/material/Icons/import_export-constant.htmlmakes not sense to me, and probably other users.

Suggestions:
- the merge arrow: https://api.flutter.dev/flutter/material/Icons/call_merge-constant.html
- the cloud download icon: https://api.flutter.dev/flutter/material/Icons/cloud_download-constant.html (this one is self explicit)

**Comment by j-fbriere** [comment]
Yes maybe the cloud download would be more intuitive indeed.

**Comment by j-fbriere** [comment]
The version [v3.5.4](https://github.com/j-fbriere/squawker/releases/tag/v3.5.4) has the new icon, so the import from the subscription list screen should be more intuitive.

**Comment by williamdes** [comment]
The new icon to import is intuitive and works great, thank you all for your work!
