### ISSUE TITLE
Add a like button 

### ISSUE THREAD

**Issue by williamdes** [j-fbriere/squawker#108]
### Describe the problem

Yes I know this app is all about local stuff, but so should be my list of likes.

Could you implement some way for me to satisfy this need to click a like button (and save the post to a list of likes)?

The goal is to have a list of likes, very much like bookmarks but for likes. It allows an user to have two lists of bookmarks and also to add to a list single click. 

Alterative feature, add an icon on each post to save it to bookmarks in one click. Not two with the drop-down list. 

### Describe the solution

One click action save to bookmarks or like button

**Comment by mrhcjones** [comment]
I tried to do this with Quacker but due to xAPI breakages, I had to shut it down. I'll attempt todo the same here!
*P.S: I am the owner (TheHCJ) of the old Quacker project, I just created a new account due to an accidental deletion :(*

**Comment by williamdes** [comment]
> I tried to do this with Quacker but due to xAPI breakages, I had to shut it down. I'll attempt todo the same here! _P.S: I am the owner (TheHCJ) of the old Quacker project, I just created a new account due to an accidental deletion :(_

Thank you for dropping a comment

I think it would be nice to have on the readme why this app was forked and who maintains it
I found this a bit messy when looking up the repo that it is a fork of fritter but now knowing why and if maybe this app is more focused onto some features that the original one

**Comment by mrhcjones** [comment]
That's because I forked fritter and tried to re-add everything. Then I realised it is best that I just contribute to squawker considering most of the work is already done. Hope that cleans things up!

**Comment by mrhcjones** [comment]
Instead of a like button I will just add an Bookmark button like in the screenshot below

![image](https://github.com/j-fbriere/squawker/assets/150591975/dd26c6ae-a48d-4f87-8162-ccc062951da2)

**Comment by mrhcjones** [comment]
@williamdes I have finally implemented a working version of this, just need to do some polishing and testing!

**Comment by williamdes** [comment]
> @williamdes I have finally implemented a working version of this, just need to do some polishing and testing!

Awesome, could you drop an apk so I can test?

**Comment by mrhcjones** [comment]
I will later today

**Comment by mrhcjones** [comment]
Here is an apk:
https://github.com/mrhcjones/Quacker/actions/runs/6868957796/job/18680705054

**Comment by mrhcjones** [comment]
It does require you to uninstall Squawker first to be able to test this apk!

**Comment by williamdes** [comment]
Awesome!
Could you also make the number of likes increment by one?

**Comment by mrhcjones** [comment]
Are you sure that is a good idea, as this feature is only local and doesn't add to the like count on the web

**Comment by mrhcjones** [comment]
Due to the similarity to the save tweet feature I am not going to be making this issue an reality. This opinion is also expressed by @j-fbriere.

**Comment by j-fbriere** [comment]
The version [v3.8.0](https://github.com/j-fbriere/squawker/releases/tag/v3.8.0) has implemented a bookmark icon (thanks @TheHCJ).

**Comment by williamdes** [comment]
Thank you!

That will do, maybe it would be less frustrating to have an option to hide the like button. I always want to click it..
