### ISSUE TITLE
VirusTotal flags Squawker with a positive

### ISSUE THREAD

**Issue by Oleepre** [j-fbriere/squawker#113]
Every version of Squawker above 3.4.4 gets a (probably) false positive in VirusTotal for TROJ_GEN.R002V01K223.
 Versions 3.4.3 and below come out clean. It would be nice to see what changed and what's triggering these results.

**Comment by mrhcjones** [comment]
Could you share the file hash so I can look into what could be causing it. I have just done a scan on v3.5.4 and nothing flagged it as malicious.

My HASH: 651e5bd2fcc58284cf85cc8279955ffa221da2c889281be5df6096d22d7c707b
VirusTotal: https://www.virustotal.com/gui/file/651e5bd2fcc58284cf85cc8279955ffa221da2c889281be5df6096d22d7c707b
