### ISSUE TITLE
[Feature Request] Add custom list of guest accounts

### ISSUE THREAD

**Issue by anyone00** [j-fbriere/squawker#152]
### Describe the problem

I'm failing to generate new guest accounts it seems.

I can generate tokens on my network (or proxies) on other devices using the curl or the js script in nitter discussions. But squawker somehow fails.

### Describe the solution

Can you please add a way to insert a list of custom guest account credentials?

related: https://github.com/j-fbriere/squawker/issues/59 https://github.com/j-fbriere/squawker/issues/72

Appreciate your hard work <3

_Originally posted by @anyone00 in https://github.com/j-fbriere/squawker/issues/45#issuecomment-1889950326_

**Comment by j-fbriere** [comment]
The file in question could have one or many credentials.
Squawker could accept the two type of format.
- Single credential:
`{"oauth_token":"...", "oauth_token_secret":"..."}`

- Multiple credentials:
```
[
  {"oauth_token":"...", "oauth_token_secret":"..."},
  {"oauth_token":"...", "oauth_token_secret":"..."},
  ...
]
```

**Comment by anyone00** [comment]
Mark the rate limited guest account like nitter does to not use them until they're unblocked. This feature shouldn't stop squawker to stop generating it's own guest accounts too.

**Comment by j-fbriere** [comment]
Version [v3.6.2](https://github.com/j-fbriere/squawker/releases/tag/v3.6.2) can import externally created Twitter/X guest accounts.
See the [wiki information](https://github.com/j-fbriere/squawker/wiki/External-Twitter-X-guest-accounts).
