### ISSUE TITLE
Any search/trends hashtag results in "no results"

### ISSUE THREAD

**Issue by Daniongithub** [j-fbriere/squawker#156]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.6.0+300012770

### Steps to reproduce the bug

Go to Trending/Search something
Enter search or click a trend
See "no results" from every query

### Expected behavior

Tweets as search result

### Actual behavior

Results aren't shown

### Screenshots/Screen recordings

![IMG_20240113_191645](https://github.com/j-fbriere/squawker/assets/135717077/22bdd7d7-264f-43b5-91ec-ee6ecd1f0b6e)

### Affected Android/Custom ROM version

Android 11/MIUI 12.5.4.0

### Affected device model

Redmi Note 8 pro

**Comment by zer0fl0w** [comment]
dupe #155

also, [look here](https://github.com/j-fbriere/squawker/issues/151#issuecomment-1890145632)

**Comment by Daniongithub** [comment]
> dupe #155
> 
> also, [look here](https://github.com/j-fbriere/squawker/issues/151#issuecomment-1890145632)

Thank you, i wanted to create a new issue since #155 gets a different error.

**Comment by j-fbriere** [comment]
The new version [v3.6.1](https://github.com/j-fbriere/squawker/releases/tag/v3.6.1) fixes the issue. 
Note that those are "enhanced" search requests that are rate limited, the same way the feed request are (50 per 15 minutes).

**Comment by Daniongithub** [comment]
I'll close the issue, i see, thanks for the support!
