### ISSUE TITLE
Large Font size

### ISSUE THREAD

**Issue by BlanXyz** [j-fbriere/squawker#158]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.6.0/1 (regression)

### Steps to reproduce the bug

1. Try to change Font size under Theme page in Settings
2. Cant have a font size smaller than 44px

### Expected behavior

Range used to consist of much smaller sizes.

### Actual behavior

Cant select smaller than 44px

### Screenshots/Screen recordings

![Screenshot](https://github.com/j-fbriere/squawker/assets/83070622/87d928ae-2626-4762-bbc4-b9d6c996c995)

### Affected Android/Custom ROM version

Android 10

### Additional information

Updating to these versions will have the smaller font sizes still selected, but will break when changed+saved.

**Comment by j-fbriere** [comment]
This is fixed in the [last build](https://github.com/j-fbriere/squawker/actions/runs/7546206939).
You could install this build if you cannot wait for a new version.
