### ISSUE TITLE
[request] make link previews in tweets optional

### ISSUE THREAD

**Issue by zer0fl0w** [j-fbriere/squawker#16]
hi again,

as already stated [here](https://github.com/j-fbriere/squawker/issues/8#issuecomment-1641547612), i would kindly like to ask if it is possible to have link previews in tweets optional as it would safe bandwidth and as they are mostly visually huge compared to the initial tweet content itself, it could let someone be more focused without them. well, hopefully.

if you are already tired of me, feel free to close (:

thanks.

**Comment by zer0fl0w** [comment]
for comparsion reasons pictures attached.

v3.1.0 clean feed [here](https://i.postimg.cc/pLzzYFcM/signal-2023-07-19-10-47-21-406.jpg) 

v3.1.6 link previews feed [here](https://i.postimg.cc/g0KMs5tp/Screenshot-20230719-104644.png)

**Comment by j-fbriere** [comment]
Version [3.1.7](https://github.com/j-fbriere/squawker/releases/tag/v3.1.7) has changed the **Leaner feeds** option from not displaying quotes to not displaying preview links.

To test it, first be sure that the option is activated, then don't forget to flush the cache of the main feed or your group by scrolling down the feed from the top.

**Comment by zer0fl0w** [comment]
that was quick. work of art. its perfect. thanks a lot. superb support.
