### ISSUE TITLE
FormatException: Unexpected end of input (at character 1)

### ISSUE THREAD

**Issue by RoonMoonlight** [j-fbriere/squawker#165]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.6.2+300012833

### Steps to reproduce the bug

1. Go to random profile page
2. Displays FormatException: Unexpected end of input (at character 1) (excluding Follower/Following tab)

### Expected behavior

It should be able to see Tweets/Post without issue

### Actual behavior

It returns error

### Screenshots/Screen recordings

![Screenshot_20240120_101706_Squawker](https://github.com/j-fbriere/squawker/assets/25527589/61c3bcec-9d4f-4472-87ad-bc7cfbc0f8df)

### Logs

N/A

### Affected Android/Custom ROM version

Android 14 / One UI 6

### Affected device model

Samsung Galaxy S22+

### Additional information

N/A

**Comment by adsarwal** [comment]
I have the same error when I view individual subscriptions.  Feeds and groups work as expected.

**Comment by imustd** [comment]
Same error, Feed is also not working  for me.

**Comment by j-fbriere** [comment]
It was working perfectly well earlier today (and all the days before). 
Yet another change by Twitter / X... 
I'll look into it.

**Comment by j-fbriere** [comment]
Just checked and it's the same type of problem that appeared recently where the "old" (v1.1) Twitter/X API calls for feeds and searches stopped working suddenly.
I guess Twitter/X is abandoning all v1.1 API requests this month. Oh well.
It may take a bit because I have to implement the new types of requests for the Profile.

**Comment by mrhcjones** [comment]
For now couldn't we just use tweet search

**Comment by mrhcjones** [comment]
I'll work on a fix for it if you want

**Comment by RoonMoonlight** [comment]
> For now couldn't we just use tweet search

Good news: `nitter.net` still works well, use it in the meantime

**Comment by mrhcjones** [comment]
Just created a draft pull request #166

**Comment by mrhcjones** [comment]
I'll work on fixing the last few things + code refactoring before I get it ready for review

**Comment by mrhcjones** [comment]
Pull request ready to be merged

**Comment by mrhcjones** [comment]
I've added apks to the pull request for those that want to test it

**Comment by j-fbriere** [comment]
@mrhcjones thank you for this "quick fix" which is a workaround using the Twitter/X API requests already implemented in Squawker.
As you know this fix uses the same type of Twitter/X API request than then one for the feeds/groups and the searches (users/tweets) which is very rate limited (50 requests per 15 minutes).
So any request to a profile will directly impact the rates for the feed/groups requests that already very rate limited. 
That is the reason why I'm reluctant to merge this fix.
The actual type of Twitter/X API requests that must be implemented for the profile are far less rate limited (500 per 15 minutes) and also will not impact the feed/groups/searches requests.

**Comment by mrhcjones** [comment]
> @mrhcjones thank you for this "quick fix" which is a workaround using the Twitter/X API requests already implemented in Squawker. As you know this fix uses the same type of Twitter/X API request that the one used for the feeds/groups and the searches (users/tweets), which are very rate limited (50 requests per 15 minutes). So any request to a profile will directly impact the rates for the feed/groups requests that already very rate limited (and inversely). That is the reason why I'm reluctant to merge this fix. The actual type of Twitter/X API requests that must be implemented for the profile, which are different types of Twitter/X API requests, are far less rate limited (500 requests per 15 minutes) and also will not impact the feed/groups/searches requests.

I understand, I'll keep the pull request open as a temp workaround for now

**Comment by mrhcjones** [comment]
These are the graphql endpoints if I don't get time to fix this 👇  
 graphUserTweets = 3JNH4e9dq1BifLxAa3UMWg/UserWithProfileTweetsQueryV2
  graphUserTweetsAndReplies = 8IS8MaO-2EN6GZZZb8jF0g/UserWithProfileTweetsAndRepliesQueryV2
  graphUserMedia = PDfFf8hGeJvUCiTyWtw4wQ/MediaTimelineV2

**Comment by j-fbriere** [comment]
Yes I'm currently implementing them, thank you.

**Comment by mrhcjones** [comment]
Ok, thank you!

**Comment by j-fbriere** [comment]
Version [v3.6.3](https://github.com/j-fbriere/squawker/releases/tag/v3.6.3) fixes the issue.
