### ISSUE TITLE
Create a Weblate

### ISSUE THREAD

**Issue by mrhcjones** [j-fbriere/squawker#167]
### Describe the problem

Currently squawker cannot be easily translated mainly due to the fact it doesn't have a translation interface

### Describe the solution

Create a weblate for the project (free for libre projects) 
https://hosted.weblate.org/accounts/login/?next=/hosting/

**Comment by j-fbriere** [comment]
I have created a [weblate project](https://hosted.weblate.org/projects/squawker/).
I'm waiting for the approval of Libre hosting, so that it won't cost me anything.

**Comment by mrhcjones** [comment]
Ok, thank you!
