### ISSUE TITLE
Import/Export is broken with v3.6.4

### ISSUE THREAD

**Issue by nooraibk** [j-fbriere/squawker#177]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.6.4

### Steps to reproduce the bug

1. Go to Setting
2. Export 
3. Import on another device

**Comment by NicoCharrua** [comment]
Experiencing this too, on 3.7.0. I cleared the data because the app was frozen. When I imported from a backup, the settings (like the theme) were imported, but not my subscriptions or saved tweets.

Android 14, Pixel 6A.

**Comment by j-fbriere** [comment]
The version [v3.7.2](https://github.com/j-fbriere/squawker/releases/tag/v3.7.2) fixes this issue.
