### ISSUE TITLE
Thank you for everything ❤️

### ISSUE THREAD

**Issue by TheHCJ** [j-fbriere/squawker#180]
From the bottom of my heart thank you. Maintaining Squawker must have been an incredibly hard job and now it's impossible I feel we all need to say thank you for making twitter bearable.

With [nitter announcing it are dead](https://github.com/zedeus/nitter/issues/1155#issuecomment-1913361757) and twitter's increasing aggression towards anonymous front ends the end of Squawker and Nitter was inevitable.

Thank you for your contributions and I can't wait to see where you go next! 👋🏼

Sources
[#983](https://github.com/zedeus/nitter/issues/983)
[Nitter d420](https://nitter.d420.de/)

**Comment by greensheeps** [comment]
> From the bottom of my heart thank you. Maintaining Squawker must have been an incredibly hard job and now it's impossible I feel we all need to say thank you for making twitter bearable.
> 
> With [nitter announcing it are dead](https://github.com/zedeus/nitter/issues/1155#issuecomment-1913361757) and twitter's increasing aggression towards anonymous front ends the end of Squawker and Nitter was inevitable.
> 
> Thank you for your contributions and I can't wait to see where you go next! 👋🏼
> 
> Sources [#983](https://github.com/zedeus/nitter/issues/983) [Nitter d420](https://nitter.d420.de/)

Thanks for making Quacker as well as @jonjomckay for making Fritter

**Comment by Devitoo** [comment]
so it is the end ? 
damn, 
thank you for your hard work ❤️
i will just use the official app now...

**Comment by VillagerTom** [comment]
Thank you for your effort! Thank you for everything!
The spirit of defying Digital Dictatorships is immortal!
![Screenshot_2024-01-30-12-32-12-88](https://github.com/j-fbriere/squawker/assets/89803422/6e858b49-0552-43d0-8e4c-80f2c89fffe0)
And if you're willing, could you please make the last release of Squawker? As an artwork.

**Comment by locuturus** [comment]
Thanks for your work!

Twitter is a mess. I can't make sense of what is or isn't working, I have this on 3 devices. One _recovered_ access today, another has not lost it ever, the third lost its guest account. What are they even doing on the backend lol.

**Comment by JoeyJoJoJr** [comment]
https://github.com/zedeus/nitter/issues/983#issuecomment-1915814449

> I do not think Zedeus is abandoning the project just yet — He is willing to explore any options the moment they become available

Nitter isn't beyond fixing.

**Comment by ajz3d** [comment]
> See you all on Nostr. 👋

Is there a Squawker-type of program for the  Nostr protocol? I'm a lurker, not a poster.

**Comment by anton-isidore** [comment]
@locuturus Not sure. But creation of the keys is only local stuff, they are generated randomly on the device, so you can just create random one and never back it up.

There is no real sign/up or login. All is local.

**Comment by locuturus** [comment]
> @locuturus Not sure. But creation of the keys is only local stuff, they are generated randomly on the device, so you can just create random one and never back it up.
> 
> There is no real sign/up or login. All is local.

In my experience it can take days, maybe even a week, before Squawker is able to access twitter after a new install. That's normal behavior for months now. I did not expect one of the installs to lose *and then recover* access at the present time with everything going on.

**Comment by sudoshindo** [comment]
Has fbriere not given a statement yet about a decision to end the project?
I'm just about ready to uninstall the app, but I kind of want to wait for the confirmation.

**Comment by sudoshindo** [comment]
To j-fbriere,
Thank you for all the effort you put into this app.
However I assume you're getting just as stressed trying to make this function correctly as some of us are while staring at blank feeds.
I think it's time to rest, you deserve it.
As for me, I'll take this app's breakage as a sign to quit Twitter.

**Comment by j-fbriere** [comment]
Thank you for your kind words.
The version [v3.7.0](https://github.com/j-fbriere/squawker/releases/tag/v3.7.0) allows you to use a throwaway regular Twitter/X account.
To add the information (username/password) of your throwaway regular Twitter/X account, go to Settings / Account and tap on the plus icon.
