### ISSUE TITLE
Keep read position in feed after refreshing

### ISSUE THREAD

**Issue by doug8888** [j-fbriere/squawker#19]
### Describe the problem

I like to read tweets in my feed in the order they are written. When the app is refreshed or closed and opened again the feed defaults to the top, the newest tweet. I then have to scroll down to find the position where I left off.

### Describe the solution

Ideally the app would remember where I was in the feed and remain in that position after refreshing. This was an option in Twidere that I previously used. Thanks

**Comment by Saroumane** [comment]
I was going to write this ! Squawker now works better than Twidere, excepted for this 'must-have' feature.

**Comment by zer0fl0w** [comment]
came here to suggest the same thing. nice to see ppl already aware of it too.

if it is possible to implement it would be a huge ux boost.

**Comment by Denny966** [comment]
Must have feature

**Comment by j-fbriere** [comment]
Version [3.2.0](https://github.com/j-fbriere/squawker/releases/tag/v3.2.0) implements this feature.
The feature is not activated by default. Must be activated in Settings / Keep feeds offset.

**Comment by zer0fl0w** [comment]
thanks a lot!

**Comment by Saroumane** [comment]
> Version [3.2.0](https://github.com/j-fbriere/squawker/releases/tag/v3.2.0) implements this feature. The feature is not activated by default. Must be activated in Settings / Keep feeds offset.

Unfortunately that is not enough in 3.2.0
What is needed : "Ideally the app would remember where I was in the feed and remain in that position after **refreshing.**"
What is done in 3.2.0 : "offset is kept for feeds when app restarts"

I just tested refreshing the feed : read position was lost and the offset was autoscrolled to the top (most recent) tweet.

In fact we need both : keeping offset position when app restarts or after a feed refresh.

**Comment by doug8888** [comment]
Yes agree with the above comment. Refreshing the feed takes me to the top of the feed.

**Comment by Denny966** [comment]
> > Version [3.2.0](https://github.com/j-fbriere/squawker/releases/tag/v3.2.0) implements this feature. The feature is not activated by default. Must be activated in Settings / Keep feeds offset.
> 
> Unfortunately that is not enough in 3.2.0 What is needed : "Ideally the app would remember where I was in the feed and remain in that position after **refreshing.**" What is done in 3.2.0 : "offset is kept for feeds when app restarts"
> 
> I just tested refreshing the feed : read position was lost and the offset was autoscrolled to the top (most recent) tweet.
> 
> In fact we need both : keeping offset position when app restarts or after a feed refresh.

Agreed, the feature doesn't do much at the moment

**Comment by j-fbriere** [comment]
What is the goal of refreshing?

**Comment by Denny966** [comment]
> What is the goal of refreshing? It is to have newer tweets, right? But then if you are not at the top to read the newer tweets then why do a refresh?

Yes it's to have newer tweets. The point is after a refresh I can continue reading my unread tweets where I left off the last time

**Comment by j-fbriere** [comment]
I'm still not sure what is your goal of doing a refresh.
If you could just explain the use case more in detail, it would help.

For me, if I want to read the unread tweets, I jut scroll up the feed, that's all.
No need top tap on refresh.

Please explain in detail your use case.

**Comment by zer0fl0w** [comment]
can confirm. feature does not work as supposed.


it should be like that:

open app. feed gets refreshed.
you have to scroll down the timeline until the point where you last left or stopped reading. then you start scrolling up again until you are done with the new tweets or stop at a certain position. 
now the app ideally have to learn/know/remember what is/was the last tweet you read.
close app or even remove squawker from recents apps.
then when you come back to squawker, you open the app again after i.e. 6 hours. timeline gets refreshed, but does not jump to top. means you are not at top with your feed at latest tweet but instead on the position/tweet where you last stopped reading or quit the app.

hopefully it is comprehensible in the words i used.

thanks for reading.

**Comment by Saroumane** [comment]
To say it in another way : the read position/offset should only change when the user use his finger to manually scroll the feed.

Let's say the feed is a book. New tweets are new pages of the book, added at the end. The read position/offset is the current page number the user is reading.
The user never wants the current page number to jump to the end of the book.

**Comment by zer0fl0w** [comment]
that hit deep. on point description. thx.

**Comment by j-fbriere** [comment]
```
it should be like that:

now the app ideally have to learn/know/remember what is/was the last tweet you read.
close app or even remove squawker from recents apps.
then when you come back to squawker, you open the app again after i.e. 6 hours. timeline gets refreshed, but does not jump to top. means you are not at top with your feed at latest tweet but instead on the position/tweet where you last stopped reading or quit the app.
```
right now what it does is:
- open the app, scroll down the feed.
- close the app or put it in recent apps mode.
- reopen the app, the feed goes directly to the timeline position before.

The only difference with what you said is that it does not refresh the feed before going to the last remembered position of the timeline. It goes directly to the last remembered position of the timeline.

My question: why it is bad?

**Comment by doug8888** [comment]
Just tried it. Opened the app and I was in the feed position I got to earlier today. No tweets above were showing so I refreshed the feed by pulling down on the screen. The new tweets were loaded but I was then at the top of the feed (newest tweet) rather than down at the last tweet I read earlier. Had to scroll down manually to find my position.

**Comment by zer0fl0w** [comment]
it is not wrong. it is correct but only partly. like the other people already mention it this thread too.
i really appreciate your support and only try to be as understandable as possible.

regarding the "issue", because it does not act this way (at least for me) when you read all the tweets, and you are on top of the feed. close the app, swipe away from recents. wait some time. i check maybe 4-5 times a day. i normally read all the tweets and leave the app with no unread tweets, means feed is on top, no more scrolling down possible.

then after open the app again, i am on top again, but already with the newest tweets loaded. so i am on top of the feed with all the unread tweets. i am not at the position of the last read tweet which was the latest, before i quit the app.

dont know how to be clearer.
hopefully another one can describe it better.

**Comment by j-fbriere** [comment]
Thank you @doug8888 and @zer0fl0w.
Now I understand the issue.
I'll look into it.

**Comment by Saroumane** [comment]
For information, no change in 3.3.0
I opened the app today, I refreshed the feed, and was instantly auto-scrolled to the most recent tweet.

**Comment by j-fbriere** [comment]
Normal, I did not find a solution yet for this issue.
I'm still working on it.

**Comment by Saroumane** [comment]
Thank you so much for developping this project. Do you have a patreon ?

**Comment by j-fbriere** [comment]
Version [3.3.1](https://github.com/j-fbriere/squawker/releases/tag/v3.3.1) fixes the reload feed issue of this feature.

**Comment by zer0fl0w** [comment]
thank you. good work.
kinda works now as expected.
reading position gets losely remembered even after coming back to the before closed app and after autorefresh it will not automatically scroll to top.
feels good to me. never expected twitter reading would be possible again after the downfall e. created.
thanks to squawker it is somewhat usable again.
so, thank you. really looking forward and hoping your app will remain and continue working. thx.

**Comment by Saroumane** [comment]
> Version [3.3.1](https://github.com/j-fbriere/squawker/releases/tag/v3.3.1) fixes the reload feed issue of this feature.

I confirm it works. It's a bit strange to see the feed going top when refreshing, and immediately going down, back to  the memorized, but that's only cosmetic. In the end, it works !

**Comment by doug8888** [comment]
Good work, thanks for doing it.

**Comment by Denny966** [comment]
Works really well, nicely done!

**Comment by j-fbriere** [comment]
Closing this issue.

**Comment by Saroumane** [comment]
Upgraded to 3.3.2 and it seems it does not work anymore.
I just opened Squawker and was set on the most recent tweet.

**Comment by igorzaks** [comment]
I'm on version v3.7.6+300014563 and it seems like sometime within the last few versions this feature regressed to only keeping my place on the feed between app restarts, but not through a refresh.
