### ISSUE TITLE
Cannot add 2FA Protected account

### ISSUE THREAD

**Issue by RoonMoonlight** [j-fbriere/squawker#193]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

3.7.0+300014374

### Steps to reproduce the bug

1. Login with 2FA protected Twitter/X account
2. Include username and password
3. The error appears

### Expected behavior

Unable to create the regular Twitter/X token error occurs

### Actual behavior

It should ask for 2FA instead of throwing errors.

### Screenshots/Screen recordings

Cannot include error message due to account needs to be privated to prevent randoms following the account sorry.

### Logs

Cannot include error message due to account needs to be privated to prevent randoms following the account sorry.

### Affected Android/Custom ROM version

Android 14 / One UI 6

### Affected device model

Samsung Galaxy S22+

### Additional information

N/A

**Comment by j-fbriere** [comment]
Which kind of 2FA protection are you using? SMS? Authentication App?

**Comment by RoonMoonlight** [comment]
> Which kind of 2FA protection are you using? SMS? Authentication App?

Authentication App

**Comment by bel57** [comment]
Hello, same issue here.
Also tried the same method used by reddit 3rd party apps, 

> pwd:2FA

 but that doesn't look like a valid format. 2FA login is not supported?

**Comment by j-fbriere** [comment]
> 2FA login is not supported?

Not yet but I'm working on it.

**Comment by j-fbriere** [comment]
Version [v3.7.1](https://github.com/j-fbriere/squawker/releases/tag/v3.7.1) implements the two factor authentication functionality.
