### ISSUE TITLE
Two factor authentication support

### ISSUE THREAD

**Issue by alanpoulain** [j-fbriere/squawker#195]
### Describe the problem

The regular account login does not support two factor authentication.

### Describe the solution

The response from the API is a subtask with the following id: `LoginTwoFactorAuthChallenge`

**Comment by j-fbriere** [comment]
> The response from the API is a subtask with the following id: LoginTwoFactorAuthChallenge

Thanks for this info. I need  a little more though.

- Following this response and after the app got the code, what is the next request to the API? 
  Is it the one with substack id: LoginAcid?

Do you have a reference to a complete example?

**Comment by alanpoulain** [comment]
I don't know, is it not documented in Twitter developper documentation?

**Comment by j-fbriere** [comment]
Version [v3.7.1](https://github.com/j-fbriere/squawker/releases/tag/v3.7.1) implements the two factor authentication functionality.

**Comment by alanpoulain** [comment]
It works, thank you very much!
