### ISSUE TITLE
Suspicious activity ask confirmation code when adding account

### ISSUE THREAD

**Issue by autogris** [j-fbriere/squawker#198]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

3.7.0

### Steps to reproduce the bug

1. Go to settings
2. Select Account
3. Select + button
4. Add information and select Save

### Expected behavior

Account should be added given correct password

### Actual behavior

Error message claims suspected activity and ask for input of a confirmation code sent by email. There is no prompt on Squawker for input this code, so trying to sign-in with regular browser on the same ip, on the same phone, using this code is successful, but have no effect on Squawker afterwards. Trying to add account again with the same ip and phone in the app generates same error with a new confirmation code, again impossible to input in the app. 

Maybe there is a form of simulate Squawker on browser with a user-agent string, then entering the code there and returning to the app to login again?

### Affected Android/Custom ROM version

Android 14

**Comment by j-fbriere** [comment]
If you try to log in to your Twitter/X account a browser (same IP and phone), do you have the same behavior?

**Comment by spaaaaam** [comment]
Hello,

Same problem on my side. I got a code 400 response with error code 366 and message "Required input 'LoginEnterAlternateIdentifierSubtask' not provided".

When using a web browser, I get asked the name of the account.

Unfortunately, answering in the browser does not unlock the app.

Thanks a lot for your outstanding work and dedication to your users!

Cheers

**Comment by j-fbriere** [comment]
@autogris @spaaaaam Could you check if version [v3.7.2](https://github.com/j-fbriere/squawker/releases/tag/v3.7.2) fixes this issue?

**Comment by spaaaaam** [comment]
Works like a charm! 

Many thanks!

**Comment by autogris** [comment]
Sorry for the delay. I confirm that 3.7.2 solves this issue! Thank you very much
