### ISSUE TITLE
View profile picture and banner

### ISSUE THREAD

**Issue by k2helix** [j-fbriere/squawker#203]
### Describe the problem

Currently, there is no way to view a bigger profile picture/banner when tapping it. I sometimes try to see some pictures that I think look great but I can only see a small version in the profile page.

### Describe the solution

When tapping on a profile picture/banner when looking a profile, the image should be viewed similar to how media attachments are viewed when tapping them on the main feed.

**Comment by j-fbriere** [comment]
Do you mean the same behavior as when we double tap on an image (double sizing the image)?

**Comment by k2helix** [comment]
Not really. I meant being able to see profile pictures as normal images, just as when tapping one image in the feed.

**Comment by j-fbriere** [comment]
Version [v3.7.6](https://github.com/j-fbriere/squawker/releases/tag/v3.7.6) implements this feature.

**Comment by k2helix** [comment]
The feature works fine. Thanks for your time!
