### ISSUE TITLE
Export Subscriptions

### ISSUE THREAD

**Issue by rjm831** [j-fbriere/squawker#21]
### Describe the problem

As per the title.  I could have sworn Squawker had this function, but can't find it anywhere now.  Thanks for considering this, and bless you (seriously) for continuing with the development of this app.

### Describe the solution

Instant and complete obedience to my every wish.

**Comment by Snyret** [comment]
Enter in configuration, Data and export your data, easy peasy.

**Comment by rjm831** [comment]
On Fritter there's option in Settings:  Backup & Restore, but not in Squawker.  And no "Data" I can find anywhere.  The only option on my Squawker app is one to import subscriptions directly from Twitter (using v3.1.7)

**Comment by j-fbriere** [comment]
Open Squawker
Tap on the settings icon at the top right
Tap on Data icon, the 4th icon at the bottom
Tap on Export

**Comment by rjm831** [comment]
Thank you.  Sorry for the post.
