### ISSUE TITLE
muted videos: start video only, keep music playing

### ISSUE THREAD

**Issue by alotbsol555** [j-fbriere/squawker#210]
### Describe the problem

on playing muted (via settings) videos an external audio player, e.g. spotify, is paused. that is annoying, there is nothing to hear…

### Describe the solution

when videos are muted via settings, they should start in "video only" mode and should not affect external audio players. the audio should switch to the audio of the video stream only when you unmute the video.

**Comment by j-fbriere** [comment]
This will be in the next version.

While we're at it, would you also like to have Squawker videos continue running in the background?

**Comment by j-fbriere** [comment]
Yes those two features (don't disrupt other app videos and play in the background) will be optional (enabled by default).

**Comment by j-fbriere** [comment]
Version [v3.7.4](https://github.com/j-fbriere/squawker/releases/tag/v3.7.4) implement this feature.

There are now two options implemented, enabled by default (under Settings / General / Media) :
  - Allows video to continue to play when Squawker is in the background
  - Allows video/music of other apps to play in the background while a video is playing in Squawker.
