### ISSUE TITLE
feature: Implement selected text activities in context menu

### ISSUE THREAD

**Issue by bagajohny** [j-fbriere/squawker#22]
### Describe the problem

I know that since we cannot login to twitter we dont get the translate option from twitter. I am not talking about that here.

My issue is that when you select any text in **squawker** there is only one option to "copy" the text. There are no additional options to share, translate text. I have installed [DeepL translate app from f-droid](https://f-droid.org/en/packages/com.example.deeplviewer/) so when I select any text in firefox browser, I get an option to translate the text using DeepL but since that option does not show up in**squawker** I am unable to translate tweets. I hope you understand what I am trying to say here. Here are some screenshots to help you understand better.

<img src=https://github.com/j-fbriere/squawker/assets/101859073/c25cbc72-7512-47d0-a268-efb0b7d633d6 width=40% height=40%> <img src=https://github.com/j-fbriere/squawker/assets/101859073/be58b46e-f67a-4df1-8fac-7e109ff20ac2 width=40% height=40%>

I notices one more issue. Twitter videos that are geoblocked dont play at all on squawker. Is this a bug or just the way it works?

### Describe the solution

We should be able to translate text by selecting it and using other translator apps.

**Comment by j-fbriere** [comment]
You can translate any tweet with the **little blue icon** at the bottom right of the tweet .

![icon_translate](https://github.com/j-fbriere/squawker/assets/49044668/dc91e09f-9b6d-4f6d-b492-e3f34591029f)

**Comment by bagajohny** [comment]
@j-fbriere  here is a comparison example


<img src=https://github.com/j-fbriere/squawker/assets/101859073/6e81cb55-b1fc-49c3-ae49-b209d8fbc87a width=40% height=40%> <img src=https://github.com/j-fbriere/squawker/assets/101859073/12f2799a-5f53-4629-9b81-d5b17ceb1c4d width=40% height=40%>

**Comment by scubajeff** [comment]
I once asked quawker for this feature. 

Basically for java/kotlin app, the following lines needed to be added in Manifest.xml

```
   <queries>
        <intent>
            <action android:name="android.intent.action.PROCESS_TEXT" />
            <data android:mimeType="text/plain" />
        </intent>
    </queries>
```

Not sure if it's the same for flutter.

**Comment by j-fbriere** [comment]
@scubajeff Squawker already has those lines added to its _AndroidManifest.xml_ file.

**Comment by j-fbriere** [comment]
Version [3.3.0](https://github.com/j-fbriere/squawker/releases/tag/v3.3.0) implements this feature.

**Comment by j-fbriere** [comment]
Closing since there is no feedback, so everything must be OK.
