### ISSUE TITLE
3.7.4 - Unable to save the Media. Twitter / Xreturned a status of 405

### ISSUE THREAD

**Issue by GMgit1** [j-fbriere/squawker#225]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

3.7.4

### Steps to reproduce the bug

Press Menu button on any Video or Pic within the app.
select download download option
Banner displays "downloading media"
Banner displays "Unable to save the Media. Twitter / Xreturned a status of 405"

### Expected behavior

Media download as per previos versions

### Actual behavior

Banner briefly  displays "downloading media"
Banner displays "Unable to save the Media. Twitter / Xreturned a status of 405"
no save location or download

### Screenshots/Screen recordings

None 

### Logs

None 

### Affected Android/Custom ROM version

Android 

### Affected device model

samsung 

### Additional information

None

**Comment by j-fbriere** [comment]
Yes I see it, I'm sorry for the inconvenience.
I will rush a new version soon.

**Comment by j-fbriere** [comment]
Version [v3.7.5](https://github.com/j-fbriere/squawker/releases/tag/v3.7.5) fixes the issue.
