### ISSUE TITLE
Replies show up in feed, when the setting is off

### ISSUE THREAD

**Issue by TheHCJ** [j-fbriere/squawker#236]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.7.6+300014563

### Steps to reproduce the bug

1. Go to feed
2. Turn off replies
3. Re-open the feed
4. See replies in the feed

### Expected behavior

1. Go to feed
2. Turn off replies
3. Re-open the feed
4. Don't see replies in the feed

### Affected Android/Custom ROM version

Android 14 / HyperOS 1

### Affected device model

Xiaomi Redmi Note 12 4G

**Comment by j-fbriere** [comment]
Version [v3.7.7](https://github.com/j-fbriere/squawker/releases/tag/v3.7.7) fixes this issue.
