### ISSUE TITLE
X.com

### ISSUE THREAD

**Issue by rsssxd** [j-fbriere/squawker#24]
### Describe the problem

Twitter will soon change its domain name to "x.com". 

### Describe the solution

A version in which the domain names that the application connects to are changed to "x.com" can be kept ready.

**Comment by selurvedu** [comment]
> right now x.com redirects me to a go daddy page to advertise that the domain is available to buy

Not anymore. https://x.com/elonmusk/status/1683171310388535296

**Comment by TheHCJ** [comment]
Already implemented this change in [Quacker](https://github.com/TheHCJ/Quacker)

**Comment by j-fbriere** [comment]
Version [3.3.0](https://github.com/j-fbriere/squawker/releases/tag/v3.3.0) implements this feature.

**Comment by j-fbriere** [comment]
Closing since there is no feedback, so everything must be OK.
