### ISSUE TITLE
Retrieve more tweets on search

### ISSUE THREAD

**Issue by Teskann** [j-fbriere/squawker#240]
### Describe the problem

Hi,

With current version, if you search tweets, you are limited to 25 tweets and cannot display more when you scroll down to the last one.

### Describe the solution

If the "infinite scroll" is too hard to implement, I think an _easy_ fix could le to use the parameter  in `searchTweets` in `lib/client/client.dart`

```dart
  static Future<TweetStatus> searchTweets(String query, bool includeReplies, {int limit = 25, String? cursor, String? cursorType, bool leanerFeeds = false, RateFetchContext? fetchContext}) async 
                                                                                          ^
```

We could for example add an option to chose the number of tweets to get, which would default to 25.

What do you think?

Cheers

**Comment by j-fbriere** [comment]
Version [v3.7.8](https://github.com/j-fbriere/squawker/releases/tag/v3.7.8) implements this feature.
By keeping scrolling there are new requests automatically made.
