### ISSUE TITLE
Downloaded images not showing in gallery

### ISSUE THREAD

**Issue by Tigriz** [j-fbriere/squawker#25]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.1.9+300003167

### Steps to reproduce the bug

Download handling is set to "save to directory", storage scopes or global storage permission produce the same bug.

1. Download any image
2. Open gallery
3. New downloaded image is not shown

### Expected behavior

Any image or video downloaded should be automatically scanned and shown in gallery in both download handling modes

### Actual behavior

Images (and videos) are not scanned and not shown in gallery when in save to directory mode.

### Screenshots/Screen recordings

https://webmshare.com/vyLbD

### Affected Android/Custom ROM version

Android 13/GrapheneOS

### Affected device model

Pixel 7a

### Additional information

Only opening them once in Files app or a reboot make them appear in the gallery.

**Comment by j-fbriere** [comment]
Version [3.3.0](https://github.com/j-fbriere/squawker/releases/tag/v3.3.0) fixes the issue.

**Comment by j-fbriere** [comment]
Closing since there is no feedback, so everything must be OK.
