### ISSUE TITLE
Squawker no longer able to fetch list of tweets

### ISSUE THREAD

**Issue by RoonMoonlight** [j-fbriere/squawker#253]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.7.7+300014723

### Steps to reproduce the bug

1. Search any user's Twitter/X profile and click on it
2. Make sure the tab is on Tweets section
3. "Couldn't find any of tweets by this user!" error appears

### Expected behavior

It should be able to fetch tweets without issues.

### Actual behavior

It does not fetch any of tweets (Only Tweets tab is affected, other thing works fine)

### Screenshots/Screen recordings

![Screenshot_20240318_124547_Squawker](https://github.com/j-fbriere/squawker/assets/25527589/0b9c497e-14f6-40a8-bf6e-91fa7ca6e585)
Empty @\PlayOverwatch Twitter/X tweets page

### Logs

N/A

### Affected Android/Custom ROM version

Android 14 / One UI 6

### Affected device model

Samsung Galaxy S22+

### Additional information

N/A

**Comment by j-fbriere** [comment]
I cannot reproduce your issue.

![Screenshot_20240318_001424_Squawker (Debug)](https://github.com/j-fbriere/squawker/assets/49044668/08528e97-e2fd-4e5d-9c82-60d8158068d5)

**Comment by RoonMoonlight** [comment]
> I cannot reproduce your issue.
> 
> ![Screenshot_20240318_001424_Squawker (Debug)](https://private-user-images.githubusercontent.com/49044668/313548417-08528e97-e2fd-4e5d-9c82-60d8158068d5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzU4NTQsIm5iZiI6MTcxMDczNTU1NCwicGF0aCI6Ii80OTA0NDY2OC8zMTM1NDg0MTctMDg1MjhlOTctZTJmZC00ZTVkLTljODItNjBkODE1ODA2OGQ1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA0MTkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MDAyNDkwYWU0OTMwN2YyNjhlZTQ5Y2Q3NWZjMDgxODVkZmQzNTU0ZWIwMWI3ZDBhMmRiOWY0MzFjYThlMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2cpBjwafx6mr1OAg6VAEEtHY-UAJYJpYjIaF3Tt9LcE)

Hmm weird, I have also accounts logged on (three of them), wonder what is causing it

**Comment by j-fbriere** [comment]
Was it working normally then suddenly this issue appeared? For instance, was it working fine yesterday?

**Comment by RoonMoonlight** [comment]
Yes it worked fine yesterday but I get why, it seems Twitter deemed that I am using VPN and considered suspicious activity and my account got locked

I am trying to recover the account and will let you know if problem is solved

**Comment by j-fbriere** [comment]
>  it seems Twitter deemed that I am using VPN and considered suspicious activity and my account got locked

Before locking your account, did Twitter/X send you an email (or a SMS if you set a phone number) to confirm that your activity was not suspicious?

**Comment by RoonMoonlight** [comment]
> > it seems Twitter deemed that I am using VPN and considered suspicious activity and my account got locked
> 
> Before locking your account, did Twitter/X send you an email (or a SMS if you set a phone number) to confirm that your activity was not suspicious?

There was no email surprisingly, it was just a CAPTCHA check

Alright, it is resolved, the cause of the issue was account lock
