### ISSUE TITLE
rearranging subscriptions duplicates subscription list

### ISSUE THREAD

**Issue by alotbsol555** [j-fbriere/squawker#258]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

3.7.8

### Steps to reproduce the bug

1. rearrange subscriptions (to see the bug more easily, rearrange something towards the end of the list)
2. stay in the subscription list

### Expected behavior

Having a *single* rearranged list of subscriptions.

### Actual behavior

after rearranging, the rearranged list is added completely as duplicate to the list each time you rearrange something, i.e. you can scroll down past the previous end of ths list.
leaving the list and coming back to subscriptions shows the correct, rearranged list only once.

### Affected Android/Custom ROM version

Android 14

**Comment by j-fbriere** [comment]
Sorry but I cannot reproduce.
The tests I did:

1- First test:
- Rearrange a couple of subscription items around the top
- Scroll down and up
- Go to Feed
- Go to Subscriptions
- Scroll down and up
- Close and reopen the app
- Go to Subscriptions
- Scroll down and up

2- Second test:
- Rearrange a couple of subscription items from around the top to around the bottom
- Scroll down and up
- Go to Feed
- Go to Subscriptions
- Scroll down and up
- Close and reopen the app
- Go to Subscriptions
- Scroll down and up

3- Third test:
- Rearrange a couple of subscription items from around the bottom
- Scroll down and up
- Go to Feed
- Go to Subscriptions
- Scroll down and up
- Close and reopen the app
- Go to Subscriptions
- Scroll down and up

It always stayed with one and only one Subscriptions list.

Please give me specific steps to reproduce.

Note: In theory if you click on the ordering type or ordering order icons, it removes the custom reordering. 
          You should do that before starting your tests of custom reordering.

**Comment by j-fbriere** [comment]
After more tests I found that there was an issue indeed. Thank you.
The version [v3.8.2](https://github.com/j-fbriere/squawker/releases/tag/v3.8.2) fixes this issue.
