### ISSUE TITLE
[REQ] Please support http/socks proxy

### ISSUE THREAD

**Issue by 0xRustlang** [j-fbriere/squawker#260]
**Describe the problem that needs solving**
A clear description of what the problem is. E.g. I'm always frustrated when [...]

Please support http/socks proxy for those reigns that blocked the website or for other use cases (networks that need it)

**Describe the solution you'd like**
A clear description of what you want to happen.

Please support http/socks proxy for those reigns that blocked the website or for other use cases (networks that need it)

Thank you very much

**Comment by j-fbriere** [comment]
It already exists.
Tap on Settings / General / Proxy then input your proxy address (supports http/https and socks5).
