### ISSUE TITLE
[REQ] Please add an option to increase font/text size of tweets

### ISSUE THREAD

**Issue by 0xRustlang** [j-fbriere/squawker#261]
**Describe the problem that needs solving**
text size in the app is really small although i set system scaling and text size of system yo maximum.

Please if may let us to increase font/text size to may be 400 or 500 percent.

(I talk about maximum value)

It will really needed.
Thank you very much

**Describe the solution you'd like**
A clear description of what you want to happen.

Please if may let us to increase font/text size to may be 400 or 500 percent.

(I talk about maximum value)

It will really needed.
Thank you very much

**Comment by j-fbriere** [comment]
It already exists.
Tap on Settings / Theme then on the Font size button (14 px) and move the slider to the right to select a bigger size.
