### ISSUE TITLE
[fr] disable animations

### ISSUE THREAD

**Issue by throwaway26425** [j-fbriere/squawker#272]
### Describe the problem

animations can't be disabled on Squawker.

https://github.com/j-fbriere/squawker/assets/85243826/c31a0d7c-e29b-42b9-84bb-d0baa270a35d

### Describe the solution

it would be great if Squawker had an option to disable all animations.

**Comment by j-fbriere** [comment]
The version [v3.8.2](https://github.com/j-fbriere/squawker/releases/tag/v3.8.2) implements this feature.
The animations are enabled by default, the option to disable it is located in Settings / General / Navigation animations.
