### ISSUE TITLE
What is this button for?

### ISSUE THREAD

**Issue by ToughDBlue** [j-fbriere/squawker#274]
Just started using Squawker and I can't figure out what this button does to the far right of other buttons under a Tweet.  
![IMG_20240401_095919](https://github.com/j-fbriere/squawker/assets/53195842/f96da0be-0ee1-424d-9c42-97faddd2232f)

**Comment by TheHCJ** [comment]
It's a translation button

**Comment by ToughDBlue** [comment]
Thank you!

**Comment by TheHCJ** [comment]
@ToughDBlue could you close this issue?

**Comment by ToughDBlue** [comment]
Sure can!
