### ISSUE TITLE
search tweets in viewed profile

### ISSUE THREAD

**Issue by alotbsol555** [j-fbriere/squawker#280]
### Describe the problem

searching for tweets from a specific user is too difficult (impossible?).

### Describe the solution

add a search button to the upper right corner in the profile view. this search finds only tweets from the currently viewed user.

**Comment by feijoey** [comment]
This would be incredibly useful if it's possible to add it.

**Comment by TheHCJ** [comment]
I'll look into this

**Comment by TheHCJ** [comment]
No, for the average user they will not understand all of the search filters
