### ISSUE TITLE
Saved Tweets Button Missing

### ISSUE THREAD

**Issue by rjm831** [j-fbriere/squawker#283]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

3.8.0

### Steps to reproduce the bug

Press on three dots icon...

### Expected behavior

Used to have a Save Tweet selection

### Actual behavior

Selection to Save Tweet is now missing (latest uodate)

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Tab A7

**Comment by feijoey** [comment]
There's now a button for bookmarking/saving tweets at the bottom of a tweet.  It's between the number of likes and the translate button. Great improvement I think.

**Comment by rjm831** [comment]
Thank you!  And a serious thanks for continuing the development - all your work is greatly appreciated.

**Comment by feijoey** [comment]
Sorry, I meant that TheHCJ added the bookmark button as part of the v3.8.0 update a couple of days ago. But I agree, the work of j-fbriere and TheHCJ and any other developers of this app is much appreciated!
