### ISSUE TITLE
Newly saved tweets added to the end of the list

### ISSUE THREAD

**Issue by zihu12** [j-fbriere/squawker#322]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.8.3+300016323

### Steps to reproduce the bug

1. Open the Application and go to saves tab(must go to the tab to reproduce)
2. go somewhere in the app and save a tweet
3. return to the saved tab and see the list

### Expected behavior

The tweet saved in step 2 added to the top of the lisr

### Actual behavior

The tweet was added to the end

### Screenshots/Screen recordings

[screen recording.zip](https://github.com/user-attachments/files/15883674/screen.recording.zip)

### Affected Android/Custom ROM version

Android 13/MIUI 14.0.8.0

### Additional information

IIRC the issue appeared a few updates before the latest version through I forgot when first appeared :(

**Comment by j-fbriere** [comment]
Thank you!
