### ISSUE TITLE
I cant login my x account

### ISSUE THREAD

**Issue by ysfcdr** [j-fbriere/squawker#327]
### Checklist

- [x] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

3.8.2

### Steps to reproduce the bug

I going to login page and i write my username and password and give me an error

### Expected behavior

log into my x account

### Actual behavior

I going to login page and i write my username and password and give me an error
The error:
![Screenshot_20240621_230019_Squawker](https://github.com/j-fbriere/squawker/assets/170194975/8a4c6ab8-0c08-4e6f-bc67-62bbb62fcabe)

### Logs

![Screenshot_20240621_230019_Squawker](https://github.com/j-fbriere/squawker/assets/170194975/0c4955db-538c-4aa7-9919-113f4ea94dcb)

### Affected Android/Custom ROM version

Android 14/One UI 6.1

### Affected device model

Samsung Galaxy Tab A9+ 8/128

**Comment by carolgamaa** [comment]
Hey, I had the same problem. Do you use any VPN services, for example Mullvad? I noticed that he had the option to "block social media" enabled. After disabling the login it worked perfectly. So it could be something related.

**Comment by ysfcdr** [comment]
> Hey, I had the same problem. Do you use any VPN services, for example Mullvad? I noticed that he had the option to "block social media" enabled. After disabling the login it worked perfectly. So it could be something related.

I use Proton VPN and I have never seen such a setting and I have the same problem whether I turn the VPN on or off (Machine Translation)

**Comment by ysfcdr** [comment]
> Hey, I had the same problem. Do you use any VPN services, for example Mullvad? I noticed that he had the option to "block social media" enabled. After disabling the login it worked perfectly. So it could be something related.

Ahh my dns mullvad and dns supports block socilal media i set my dns to base.dns.mullvad.net and problem solved
