### ISSUE TITLE
Large groups (~200) no longer loading

### ISSUE THREAD

**Issue by autogris** [j-fbriere/squawker#343]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

3.8.3

### Steps to reproduce the bug

1. Add at least 200 profiles to a group
2. Click on the group name

### Expected behavior

Show the posts of the content profiles. The group was working as expected until yesterday.

### Actual behavior

Blank content, no posts are shown.

### Affected Android/Custom ROM version

Android 14

### Affected device model

Galaxy A54

**Comment by Go-rom** [comment]
Hi,
I think it's not about the group size.
I ve got one with less than ten accounts inside and i'm encountering this issue too.

**Comment by autogris** [comment]
Started working again, don't know what happened.
