### ISSUE TITLE
Refresh button in the top bar doesn't work

### ISSUE THREAD

**Issue by anyone00** [j-fbriere/squawker#35]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

version 3.3.0 versionCode 300003177  

### Steps to reproduce the bug

1. open the app
2. follow some account
3. go to feed page
4. press the refresh button

bh the refresh button i refer to the one at the top bar between search and move to top. 

### Expected behavior

refresh the feed

### Actual behavior

does nothing

### Logs

E/flutter (18095): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(no such column: group_id (code 1 SQLITE_ERROR): , while compiling: DELETE FROM feed_group_chunk WHERE group_id = ?) sql 'DELETE FROM feed_group_chunk WHERE group_id = ?' args [-1]

### Affected Android/Custom ROM version

Android 13

### Affected device model

Pixel 6a

**Comment by j-fbriere** [comment]
Version [3.3.1](https://github.com/j-fbriere/squawker/releases/tag/v3.3.1) should fix the issue.

**Comment by anyone00** [comment]
Thanks
