### ISSUE TITLE
Wide video doesn't play after going fullscreen

### ISSUE THREAD

**Issue by anyone00** [j-fbriere/squawker#37]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

version 3.3.0 versionCode 300003177

### Steps to reproduce the bug

1. Go to any video tweet that's not vertical (16:9 wide) example https://twitter.com/elonmusk/status/1686941773824757761
2. Start playing the video
3. Switch to fullscreen

### Expected behavior

Video continues playing

### Actual behavior

Video stops playing

### Logs

E/soundtrigger(779): audio_extn_sound_trigger_update_stream_status: invalid input device 0x0, for event 2

E/JavaBinder(1654): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 808)

### Affected Android/Custom ROM version

Android 13

### Affected device model

Pixel 6a

### Additional information

It is worth mentioning that if the video is vertical it plays the video fine after going full screen

**Comment by tripinside** [comment]
Same here with 3.3.1
Android 13 lineageos gsi
Moto g9 play

**Comment by Waredane** [comment]
Hi,
Same here with 3.3.1
Android 10 resurrection remix
redmi note 9 pro

**Comment by j-fbriere** [comment]
Version [3.3.3](https://github.com/j-fbriere/squawker/releases/tag/v3.3.3) fixes this issue.

**Comment by tripinside** [comment]
> Version [3.3.3](https://github.com/j-fbriere/squawker/releases/tag/v3.3.3) fixes this issue.

Thank you for all work

**Comment by j-fbriere** [comment]
Closing the issue as resolved.
