### ISSUE TITLE
Unable to create group because [Ok] is outside dialog due to longer german button labels

### ISSUE THREAD

**Issue by bentolor** [j-fbriere/squawker#38]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

3.3.0

### Steps to reproduce the bug

1. Switch locale to German
2. Open Create Group dialog
3. Ok button is outside box and unclickable.

### Expected behavior

I should be able to click Ok. The buttons should wrap.

### Actual behavior

Clicking OK just closes the dialog.

### Screenshots/Screen recordings

![image](https://github.com/j-fbriere/squawker/assets/588260/79512aae-3a5c-4251-87ed-07d296a5598a)

### Affected Android/Custom ROM version

LoS 18.1

### Affected device model

OnePlus 3T

**Comment by j-fbriere** [comment]
Version [3.3.2](https://github.com/j-fbriere/squawker/releases/tag/v3.3.2) fixes this issue.

**Comment by bentolor** [comment]
Thank you!

**Comment by j-fbriere** [comment]
Closing this issue.
