### ISSUE TITLE
Option in settings to increase text size in the app

### ISSUE THREAD

**Issue by doug8888** [j-fbriere/squawker#40]
### Describe the problem

Even though I have my phone set to the largest font size available, I still find it a bit too small in Squawker.

### Describe the solution

An option in settings to adjust font size (like Twidere had) would be useful.

**Comment by j-fbriere** [comment]
Never used Twidere. Could you give me more details about the option? What is the font sizes available to choose?

**Comment by doug8888** [comment]
I've taken a couple of screenshots of the settings page where the option is shown. And one showing the largest font size (24sp)

![Screenshot_20230809-223624_Twidere](https://github.com/j-fbriere/squawker/assets/68959902/d6716aa8-fb4a-437a-9af6-e214e1036585)

![Screenshot_20230809-223642_Twidere](https://github.com/j-fbriere/squawker/assets/68959902/fcd7cab1-26d7-4931-8309-4ea2b09e9c01)

![Screenshot_20230809-223739_Twidere](https://github.com/j-fbriere/squawker/assets/68959902/7bbb99ce-d6f5-4f08-ba8a-610201fc3064)

**Comment by j-fbriere** [comment]
Version [3.3.2](https://github.com/j-fbriere/squawker/releases/tag/v3.3.2) implements this feature.

**Comment by doug8888** [comment]
Great work, thanks

**Comment by j-fbriere** [comment]
Closing this issue.
