### ISSUE TITLE
Videos are downloaded in the worst available quality

### ISSUE THREAD

**Issue by votemp** [j-fbriere/squawker#48]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.4.1+300003190

### Steps to reproduce the bug

Download a video

### Expected behavior

The best available quality of the video is downloaded (for example 720x1280)

### Actual behavior

The worst available quality of the video is downloaded (for example 320x568)

### Additional information

Patch below fixes it for me:
```
diff --git a/lib/tweet/_video.dart b/lib/tweet/_video.dart
index 66dfc9a..27879c0 100644
--- a/lib/tweet/_video.dart
+++ b/lib/tweet/_video.dart
@@ -40,7 +40,7 @@ class TweetVideoMetadata {
         .where((e) => e.bitrate != null)
         .where((e) => e.url != null)
         .where((e) => e.contentType == 'video/mp4')
-        .sorted((a, b) => a.bitrate!.compareTo(b.bitrate!))
+        .sorted((a, b) => b.bitrate!.compareTo(a.bitrate!))
         .map((e) => e.url)
         .firstWhereOrNull((e) => e != null);
```

**Comment by j-fbriere** [comment]
I don't know if its a bug.
Maybe it was designed this way first to lower the bandwidth usage in case of downloads.
I would rather create an optional settings for this.

**Comment by j-fbriere** [comment]
The version [3.4.2](https://github.com/j-fbriere/squawker/releases/tag/v3.4.2) implements the option to download videos with the best quality available.
To modify the option, go to: _Settings_ / _Download videos with best quality_ (the option is deactivated by default).

**Comment by j-fbriere** [comment]
Glad it works. Closing the issue then.
