### ISSUE TITLE
No Audio on any Videos

### ISSUE THREAD

**Issue by rjm831** [j-fbriere/squawker#50]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.4.2+300003196

### Steps to reproduce the bug

Any video in my feed

### Expected behavior

Audio with Video playback

### Actual behavior

Total silence as if no audio track.  The video playback works fine otherwise.

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Tab a7, stock, no root

**Comment by j-fbriere** [comment]
This is not a bug.
The videos are muted by default. 
You just have two options: 
- Unmute each video after start playing it.
- Uncheck the setting _Mute videos_ so that all the videos are no more muted by default.

**Comment by rjm831** [comment]
Now I really feel like an idiot!  Thanks for pointing it out.
