### ISSUE TITLE
Show a tweet count somewhere

### ISSUE THREAD

**Issue by theBoatman** [j-fbriere/squawker#61]
### Describe the problem

Currently when scrolling upwards there is no visual indication how many tweets there are to read ahead.

### Describe the solution

It would be cool to have the tweets in the timeline numbered, for example in the right top corner of each tweet. So that I can see that I am currently reading the tweet number 10 for example, knowing that there are 9 more up to read.

**Comment by TheHCJ** [comment]
This should be simple to implement, I'll work on it

**Comment by j-fbriere** [comment]
The version [3.4.4](https://github.com/j-fbriere/squawker/releases/tag/v3.4.4) implements this feature in the case of feed/groups when the keep offset option is activated.

**Comment by theBoatman** [comment]
Works great. Thanks!
