### ISSUE TITLE
Clicking on tweets sometimes shows sponsored content/Ads

### ISSUE THREAD

**Issue by Panther7170** [j-fbriere/squawker#63]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.4.3+300003201

### Steps to reproduce the bug

1. Click on a random tweet
2. View Replies
3. Sometimes, you will notice a completely unrelated tweet (not reply) that is clearly an ad or promoted content.

### Expected behavior

No sponsored content or ads would be shown.

### Actual behavior

After viewing some replies you will see an ad buried with the replies.

### Screenshots/Screen recordings

![Screenshot_20230901-022245](https://github.com/j-fbriere/squawker/assets/125446389/9d1498cf-e35c-47ae-9a74-af64a998fbb0)

### Affected Android/Custom ROM version

Graphene OS TQ3A.230805.001.2023080800

### Affected device model

Pixel 6

### Additional information

Links to tweets for reference:
https://twitter.com/MishaalRahman/status/1697271293492519368
Ad: https://twitter.com/Goodergear/status/1694968459854250137

**Comment by j-fbriere** [comment]
Can you provideo the link to the answer by zedeus.

**Comment by j-fbriere** [comment]
That's not helpful. The link ask me to install some stuff, which I won't do. Anyway I found the parameter in question and made a fix. Will be on the next release.

**Comment by j-fbriere** [comment]
The version [3.4.4](https://github.com/j-fbriere/squawker/releases/tag/v3.4.4) fixes the issue.
