### ISSUE TITLE
[fr] option to remove pop-up confirmation when closing the app

### ISSUE THREAD

**Issue by useless642** [j-fbriere/squawker#68]
### Describe the problem

currently, there's no way to disable this pop-up confirmation when closing the app:

![Screenshot_2023-09-06_00-52-30](https://github.com/j-fbriere/squawker/assets/85243826/6d571448-188b-4b0b-9084-9f21ebb57cd8)

### Describe the solution

it would be great to have an option to disable it.

**Comment by j-fbriere** [comment]
The version [3.4.4](https://github.com/j-fbriere/squawker/releases/tag/v3.4.4) implements an option to enable or not a confirmation when closing the app.

**Comment by useless642** [comment]
it works! thank yo so much.

**Comment by j-fbriere** [comment]
you're welcome.
closing the issue.
