### ISSUE TITLE
enhancement: import information and subscriptions from Fritter

### ISSUE THREAD

**Issue by Wjxfi** [j-fbriere/squawker#7]
I couldn't find how to do a non-bug issue

I need it because my fritter stopped working.

**Comment by j-fbriere** [comment]
> I need it because my fritter stopped working.

There is a functional Fritter version in the ci build.
Just download the following [apk file](https://github.com/jonjomckay/fritter/suites/14085021499/artifacts/787559184) and install it.

**Comment by j-fbriere** [comment]
Since there were no feedback following my answer, I'm closing this issue.
