### ISSUE TITLE
[enhancement] Add "hide from feed" option in profiles

### ISSUE THREAD

**Issue by 0xblur** [j-fbriere/squawker#75]
# Describe the problem

Profiles added to a group are also added to the subscription list which makes the group called "All" useless because its the same as the Feed.

It would be great to save profiles without necessarily having them displayed in your feed because you don't want some profiles in your general updates.

# Describe the solution

Twidere had this option to "mute" a profile, but It will still show his tweets if you search him, look at his profile, or read a custom list. This is like a "Hide from feed" option that you can tick on a user to avoid showing anything about him in your feed.

**Comment by j-fbriere** [comment]
Version [v3.5.1](https://github.com/j-fbriere/squawker/releases/tag/v3.5.1) implement this feature.
The option is available when tapping on the subscribe/unsubscribe user icon.

**Comment by j-fbriere** [comment]
closing this issue
