### ISSUE TITLE
Nitter instances in AndroidManifest.xml are out of date

### ISSUE THREAD

**Issue by tibbsbrookside** [j-fbriere/squawker#81]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.4.4+300012183

### Steps to reproduce the bug

1. Go to Settings - Apps - Squawker.
2. Go to "Open by default".
3. Go to "Add link".
4. Try to add links from https://github.com/zedeus/nitter/wiki/Instances.

### Expected behavior

All instances are available.

### Actual behavior

Some instances are available.

### Affected Android/Custom ROM version

Android 13 / LineageOS 20

### Affected device model

Samsung Galaxy S10

### Additional information

I believe this is just that the Nitter instances listed in android/app/src/main/AndroidManifest.xml have gotten out of date. I guess the list changes fairly regularly. If the list could be updated it would be appreciated. Thanks.

**Comment by j-fbriere** [comment]
Version [3.5.0](https://github.com/j-fbriere/squawker/releases/tag/v3.5.0) fixes this issue.

**Comment by j-fbriere** [comment]
closing this issue.
