### ISSUE TITLE
Remove 'are you sure you want to close squawker' dialog

### ISSUE THREAD

**Issue by mrfricks** [j-fbriere/squawker#82]
### Describe the problem

Could we have an option to remove the 'are you sure you want to close dialog'.  

I mainly use squawker to display twitters links from other apps such as telegram, and it's annoying having to confirm that I want to close sqauwker when returning back to the app.

Thanks

### Describe the solution

Option to turn off 'are you sure you want to close dialog'

**Comment by kmantel** [comment]
There's an option to disable it now https://github.com/j-fbriere/squawker/issues/68

**Comment by mrfricks** [comment]
I hadn't noticed that it had already been fixed.
Thankyou!
