### ISSUE TITLE
[Bug] Retweets on Feed display the wrong username

### ISSUE THREAD

**Issue by Oleepre** [j-fbriere/squawker#9]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.1.2+300003146

### Steps to reproduce the bug

1. Go to the "Feed" tab.
2. See retweets from people you're subscribed to.
3. Notice the wrong username.
4. Check the user's profile to see the right one.

### Expected behavior

Retweets in the "Feed" should display the Original username and profile picture first, with a "[user] retweeted [time] ago" like they did before and they currently do in each profile.

### Actual behavior

Retweets in the "Feed" show the username and profile picture of the user who did the retweet, instead of the user who did the first post.
 They also display:
 -The text RT@[OGusername]
 - A non-clickable t.co link pointing to the original tweet.

**Comment by j-fbriere** [comment]
I made the fix.
The fix is with the [version 3.1.3](https://github.com/j-fbriere/squawker/releases/tag/v3.1.3).

**Comment by GrosMatou27** [comment]
After installing the last update, I still have the "problem". 
It shows the profile of the user who retweet, instead of the user who posted the initial tweets, with RT@[OGusername]
